services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U admin -d twitter"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  # twitter:
  #   build: .
  #   container_name: twitter_container
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/twitter
  #   depends_on:
  #     postgres:
  #       condition: service_healthy