# version: '3.9'
# services:
  # flask_app:
  #   image: flask_app
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./db/:/var/lib/postgresql/data
  #   command:
  #     - 'postgres'
  #     - '-c'
  #     - 'log_destination=stderr'
  #     - '-c'
  #     - 'logging_collector=on'
  #     - '-c'
  #     - 'log_directory=/var/lib/postgresql/data/pg_log'
