services:
  # twitter:
  #   build: .
  #   container_name: twitter_container
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://admin:admin@db:5432/twitter
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # volumes:
    #   - appnetpg:/var/lib/postgresql/data
# volumes:
#   appnetpg: