version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: twitter
    ports:
      - "5432:5432"
  # flask_app:
  #   image: flask_app
  #   build: .
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - postgres